import { initSlideMenu } from './components/slide-menu.js';
import { initStickyHeader } from './components/sticky-header.js';
import { initHeroIntro } from './animations/hero-intro.js';
import { initStats } from './animations/stats.js';
import { initInvestorsCarousels } from './components/investors-carousel.js';
import { initInvestorCardTilt } from './components/investor-card-tilt.js';
import { initCompaniesCarousels } from './components/companies-carousel.js';
import { initMoreThanCapital } from './components/more-than-capital.js';
import { initPodcastQuotesCarousels } from './components/podcast-quotes-carousel.js';
import { initVisionCarousels } from './components/vision-carousel.js';
import { initLatestUpdatesCarousels } from './components/latest-updates-carousel.js';
import { initPortfolioCarousels } from './components/portfolio-carousel.js';
import { initPortfolioFilters } from './components/portfolio-filter.js';
import { initNuJourneyTimelines } from './components/nu-journey-timeline.js';
import { initAboutTeamSort } from './components/about-team-filter.js';
import { initInitiativesFilter } from './components/initiatives-filter.js';
import { initNupodFilter } from './components/nupod-filter.js';
import { initPitchFlow } from './components/pitch-flow.js';
import { initPitchVoiceInput } from './components/pitch-voice-input.js';

initSlideMenu();
initStickyHeader();
initHeroIntro();
initStats();
initInvestorsCarousels();
initInvestorCardTilt();
initCompaniesCarousels();
initMoreThanCapital();
initPodcastQuotesCarousels();
initVisionCarousels();
initLatestUpdatesCarousels();
initPortfolioCarousels();
initPortfolioFilters();
initNuJourneyTimelines();
initAboutTeamSort();
initInitiativesFilter();
initNupodFilter();
initPitchFlow();
initPitchVoiceInput();
